version: '3'
services:
  sqt_test:
    build: ./sqt_test
    ports:
      - "5432:5432"
    networks:
      - tradesnetwork

  jupiter_test:
    build: ./jupiter_test
    ports:
      - "8888:8888"
    networks:
      - tradesnetwork

networks:
  tradesnetwork: